name: Build Android APK (Frass Predictor)

on:
  workflow_dispatch:
  push:
    paths:
      - 'FrassPredictorApp.zip'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    # Use a container that already has Android SDK + Gradle
    container: mingc/android-build-box:1.17.0

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: apt-get update && apt-get install -y unzip

      - name: Unzip project
        run: unzip -q FrassPredictorApp.zip

      - name: Build debug APK (using preinstalled Gradle)
        working-directory: FrassPredictorApp
        run: gradle assembleDebug --no-daemon

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: frass-apk
          path: FrassPredictorApp/app/build/outputs/apk/debug/app-debug.apk