name: Build Android APK (Frass Predictor)

on:
  workflow_dispatch:
  push:
    paths:
      - 'FrassPredictorApp.zip'
      - '.github/workflows/build.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip

      - name: Unzip project
        run: unzip -q FrassPredictorApp.zip

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Make gradlew executable
        working-directory: FrassPredictorApp
        run: chmod +x ./gradlew

      - name: Build debug APK
        working-directory: FrassPredictorApp
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: frass-apk
          path: FrassPredictorApp/app/build/outputs/apk/debug/app-debug.apk