name: Build Android APK (Frass Predictor)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # image contains Android SDK + NDK + build-tools + Gradle already
    container: alvrme/alpine-android:android-34-jdk17

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install unzip
        run: apk add --no-cache unzip bash

      - name: Unzip project
        run: unzip -q FrassPredictorApp.zip

      - name: Build APK
        working-directory: FrassPredictorApp
        run: ./gradlew assembleDebug || gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: frass-apk
          path: FrassPredictorApp/app/build/outputs/apk/debug/app-debug.apk